## Task 1:

In [1]:
try:
    x = 5 / 0
except:
    print("Error dividing by zero")
finally:
    print("finally executed!")

Error dividing by zero
finally executed!


In [2]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [3]:
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 
for i in subjects:
    for j in verbs:
        for k in objects:
            print(" ".join((i,j,k)))

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2:

In [4]:
import numpy as np
n = 4
m = [1, 2, 3, 5, 6]
v = []
for i in m:
    v.append(([i**j for j in range(n)]))
print(np.array(v))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]
 [  1   6  36 216]]


In [5]:
import numpy as np
x = np.array([1, 2, 3, 5, 6])
np.vander(x, N=len(x))

array([[   1,    1,    1,    1,    1],
       [  16,    8,    4,    2,    1],
       [  81,   27,    9,    3,    1],
       [ 625,  125,   25,    5,    1],
       [1296,  216,   36,    6,    1]])

In [10]:
N=7
np.column_stack([x**(N-1-i) for i in range(N)])

array([[    1,     1,     1,     1,     1,     1,     1],
       [   64,    32,    16,     8,     4,     2,     1],
       [  729,   243,    81,    27,     9,     3,     1],
       [15625,  3125,   625,   125,    25,     5,     1],
       [46656,  7776,  1296,   216,    36,     6,     1]], dtype=int32)